In [7]:
import numpy as np
array = np.arange (12)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
#維度
array.ndim

1

In [9]:
#形狀
array.shape

(12,)

In [10]:
#元素的數量
array.size

12

In [11]:
#改變形狀
array1 = array.reshape(3,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
print(array1.ndim)
print(array1.shape)

2
(3, 4)


In [13]:
array2 = array.reshape((3,2,2))
array2

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [15]:
print(array2.ndim)
print(array2.shape)

3
(3, 2, 2)
